# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceca119cedc7541bc9d58efb8741f68a7d0e207316e1bae0777b95a5195dc231eacbb5ac626a9b3d8506bcc25545aed8c29dff2167055df9a3e38bea80bef2fa

test:
  secret_key_base: 0a34125912ee85108759f09b87f799b8226e220fbbe1c648a7da6abd16ebaededc6e3b0d117528405e4f4c851b7202d2115f53fc98458aa60ef47fbeea8a2432

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
